### ISSUE TITLE
Scroll invalid inputs into view port on form submission

### ISSUE THREAD

**Issue by doobry-systemli** [jelhan/croodle#273]
When you miss a required input at a poll with lots of options, it's confusing that "nothing happens" when pressing the save button.

In fact there is a warning about missing input next to the missed field (which is good), but that very field might not be visible when pressing the save button.

My suggestion would be to additionally place a warning next to the save button, something along the lines of "you forgot to fill out a required field, see above".

**Comment by jelhan** [comment]
Thanks for the quick feedback! Actually I had a similar issue at work a few days ago. There we decided to scroll to the first invalid control if it's out of view port. Do you think that would work as well for Croodle? @sappor0 Any UX concerns?

**Comment by doobry-systemli** [comment]
> At work we fixed it by scrolling to the first invalid control if it's out of view port.

Sure, that would work as well and probably would be even more user friendly.

**Comment by sappor0** [comment]
> Thanks for the quick feedback! Actually I had a similar issue at work a few days ago. At work we fixed it by scrolling to the first invalid control if it's out of view port. Do you think that would work as well for Croodle? @sappor0 Any UX concerns?

AFAIK this is the accepted best practice for input validation errors. We just need to find a way to move to the tab item with the input element in it.

**Comment by jelhan** [comment]
> We just need to find a way to move to the tab item with the input element in it.

It shouldn't be possible to transition to finish a step in form creation wizard if the current state is invalid. Therefor there shouldn't be a case in which a transition is required to show the validation feedback. Otherwise this would be way more complex.

Also the form elements should always be above submit button. So this one should only be about checking if first invalid form control is above current view port and scrolling up if so.

**Comment by jelhan** [comment]
I've updated the issue title to reflect the discussed solution.

**Comment by doobry-systemli** [comment]
Unfortunately, your fix doesn't work as expected. It's good that croodle now shows "An answer must be selected" under each missing input, but at least in my tests, it doesn't scroll back to the first missing input. Here's the test poll that I used: https://www.systemli.org/poll/#/poll/RjA1c7RmmP/participation?encryptionKey=Y8El8X6a7zhL44xhnzDOSx0BgBDj0IbVl2x6LiAI

**Comment by doobry-systemli** [comment]
By the way, I used Firefox 70.0.1 on Linux in my tests.

**Comment by jelhan** [comment]
Can reproduce that bug in Firefox (but not in Chrome). It always scrolls up but sometimes not far enough. It seems to work if all validation errors are visible before. If submitting causes some validation errors to become visible and causes the transition, it transitions up but not far enough. Could you open an issue for that one?

**Comment by jelhan** [comment]
The bug in Firefox should be fixed by #288 .

**Comment by doobry-systemli** [comment]
Unfortunately, it still doesn't work for me on Firefox 70.0.1. When I participate at [this test poll](https://www.systemli.org/poll/#/poll/qK185OULdT/participation?encryptionKey=ZZmE0ELzPZ3WV3r0qMPsJWQF69wHWsZ5tnXLaocx) and only fill out a few options, no scroll happens at all when hitting the save button.

**Comment by jelhan** [comment]
> Unfortunately, it still doesn't work for me on Firefox 70.0.1. When I participate at [this test poll](https://www.systemli.org/poll/#/poll/qK185OULdT/participation?encryptionKey=ZZmE0ELzPZ3WV3r0qMPsJWQF69wHWsZ5tnXLaocx) and only fill out a few options, no scroll happens at all when hitting the save button.

@doobry-systemli Tried to reproduce the bug. Faced #301 and #302. Is one of these the bug you are facing? Or did you noticed a third one?

**Comment by doobry-systemli** [comment]
@jelhan: Yep, preety much sounds like #301. To be honest, I dont' really understand the technical details you're discussing in #301 and #302, but #301 seems to describe what I'm facing. #302 seems to be mobile-related, so it's unrelated.
